"""added full name column

Revision ID: f937cc135515
Revises: c0fc072389ad
Create Date: 2025-07-16 12:08:57.319034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f937cc135515'
down_revision: Union[str, Sequence[str], None] = 'c0fc072389ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE users
        SET full_name = first_name || ' ' || last_name
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
